### PR TITLE
Feat: Update Offer Utm Params

### PR DESCRIPTION
**Pull request by lordkiz**
This PR addresses:
[CX-3503]
[CX-3504]
[CX-3505]

### Description
Avails the right utm params for offers

[CX-3503]: https://artsyproduct.atlassian.net/browse/CX-3503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-3504]: https://artsyproduct.atlassian.net/browse/CX-3504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-3505]: https://artsyproduct.atlassian.net/browse/CX-3505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MounirDhahri — APPROVED** [review]
Nice! thanks 🙌

**Review by dariakoko — COMMENTED** [review]
Sorry for the late review.
@lordkiz Do you mind having a 15 mins call talking about this PR? This is something new for me, I would like to understand how it works

**Comment by lordkiz** [comment]
> Sorry for the late review. @lordkiz Do you mind having a 15 mins call talking about this PR? This is something new for me, I would like to understand how it works

Sure.

**Comment by dariakoko** [comment]
Thnaks! I'll put some time into your calendar. Feel free to suggest another time

**Pull request merged**
