### PR TITLE
feat(consignment): updated copy on Artsy Commission & Partner Commiss…

### PR DESCRIPTION
**Pull request by angelagasparyan**
ksnip_20210422-015332
ksnip_20210422-015303

…ion fields

Refs CX-1332

### CODE REVIEW

**Comment by bhoggard** [comment]
It looks like the test text needs to be updated.

**Comment by angelagasparyan** [comment]
> It looks like the test text needs to be updated.

**Comment by angelagasparyan** [comment]
> It looks like the test text needs to be updated.

Yes. I updated it.

**Comment by bhoggard** [comment]
Sorry, I just noticed the extra space before the `)` on both additions. Can you fix that?

**Comment by angelagasparyan** [comment]
> Sorry, I just noticed the extra space before the `)` on both additions. Can you fix that?

yes of course :)

**Pull request merged**
