### PR TITLE
 feat(submission): Add UTM fields

### PR DESCRIPTION
**Pull request by angelagasparyan**
Refs [CX-1399]

[CX-1399]: https://artsyproduct.atlassian.net/browse/CX-1399

### CODE REVIEW

**Review by olerichter00 — APPROVED** [review]
Looks great 👍

**Review by bhoggard — CHANGES_REQUESTED** [review]
Based on the description in https://artsyproduct.atlassian.net/browse/CX-1269 we need to add these to display in

https://github.com/artsy/convection/blob/master/app/views/admin/submissions/show.html.erb

if present.

**Comment by angelagasparyan** [comment]
> Based on the description in https://artsyproduct.atlassian.net/browse/CX-1269 we need to add these to display in
> 
> https://github.com/artsy/convection/blob/master/app/views/admin/submissions/show.html.erb
> 
> if present.

This is only first subtask

**Comment by bhoggard** [comment]
OK, I see. We should be OK once the conflict is fixed.

**Comment by angelagasparyan** [comment]
@bhoggard conflict is fixed ))

**Review by bhoggard — APPROVED** [review]

**Pull request merged**
