### PR TITLE
feat(submission): show submission source

### PR DESCRIPTION
**Pull request by angelagasparyan**
ksnip_20210628-230331
Refs CX-1269

### CODE REVIEW

**Comment by bhoggard** [comment]
Artyom to follow up and see if Consignment team is expecting any labels for the Source.

**Review by bhoggard — APPROVED** [review]

**Comment by angelagasparyan** [comment]
> Artyom to follow up and see if Consignment team is expecting any labels for the Source.

OK )

**Comment by bhoggard** [comment]
@angelagasparyan can you fix the merge conflict before merging?

**Comment by angelagasparyan** [comment]
> @angelagasparyan can you fix the merge conflict before merging?

@bhoggard sorry but my computer has a problems and now i can't fix the conflict.

**Comment by angelagasparyan** [comment]
@bhoggard the conflict is fixed.

**Pull request merged**
